"""
Shared ground-truth extraction for all benchmark and attack scripts.
Covers all 5 narrative templates generated by narrative_synth.py.
"""

import os
import re
import glob


# Patterns that cover ALL 5 templates
ENTITY_PATTERNS = {
    # Template 1,2,5: "transaction {uuid}"
    'txn_explicit': r'transaction ([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})',
    # Template 4: "Ref: {uuid}"
    'txn_ref':      r'Ref: ([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})',
    # All templates: "account {IBAN}"
    'acct':         r'account ([A-Z]{2}[A-Z0-9]{10,})',
}

# Query templates per entity type
QUERY_TEMPLATES = {
    'txn_explicit': 'details for transaction {id}',
    'txn_ref':      'reference {id} details',
    'acct':         'account {id} history',
}


def extract_ground_truth(data_roots):
    """
    Extract ground-truth queries from all organization directories.
    
    Returns list of {query, target_file, target_org, entity_type, entity_id}
    
    Each file produces at most one query per entity type to avoid
    duplication bias (a file with both txn and acct generates 2 queries).
    """
    gt = []
    seen = set()  # (org, filename, entity_type) to avoid duplicates

    for org_name, data_dir in data_roots.items():
        for path in sorted(glob.glob(os.path.join(data_dir, "*.txt"))):
            fn = os.path.basename(path)
            with open(path, 'r', encoding='utf-8') as f:
                text = f.read()

            for etype, pattern in ENTITY_PATTERNS.items():
                m = re.search(pattern, text)
                if m:
                    eid = m.group(1)
                    key = (org_name, fn, etype)
                    if key not in seen:
                        seen.add(key)
                        query = QUERY_TEMPLATES[etype].format(id=eid)
                        gt.append({
                            'query': query,
                            'target_file': fn,
                            'target_org': org_name,
                            'entity_type': etype,
                            'entity_id': eid,
                        })
    return gt


def validate_ground_truth(gt, data_roots):
    """
    Sanity checks on ground truth.
    Prints warnings for any issues.
    """
    total_files = sum(len(glob.glob(os.path.join(d, "*.txt")))
                      for d in data_roots.values())
    files_covered = len(set((g['target_org'], g['target_file']) for g in gt))

    print(f"  Total files: {total_files}")
    print(f"  Files with queries: {files_covered} ({100*files_covered/total_files:.0f}%)")
    print(f"  Total queries: {len(gt)}")

    # Check for cross-org ID collisions
    id_to_orgs = {}
    for g in gt:
        eid = g['entity_id']
        id_to_orgs.setdefault(eid, set()).add(g['target_org'])
    collisions = {eid: orgs for eid, orgs in id_to_orgs.items() if len(orgs) > 1}
    if collisions:
        print(f"  WARNING: {len(collisions)} entity IDs appear in multiple orgs!")
    else:
        print(f"  OK: All entity IDs are org-unique.")

    return files_covered == total_files
